//ob_splash
//————————————————————————————————————————————————————————————————————————————————————————————————————
depth=-1000;
//
text_rel_y=0;
text_potential_y=text_rel_y;
text_color=c_white;
//
secret_code=0;
secret_code_time=0;
secret_code_time_max=60;